# Generated by Django 5.2.4 on 2025-07-07 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='quantity',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='value_paid_in_naira',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
    ]
