# Generated by Django 5.2.4 on 2025-07-18 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_transaction_quantity_transaction_value_paid_in_naira'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='buyer',
            new_name='seller',
        ),
    ]
