# Generated by Django 5.2.4 on 2025-07-18 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_alter_transaction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='receiving_address',
            field=models.CharField(max_length=42, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='sending_address',
            field=models.CharField(max_length=42, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_hash',
            field=models.CharField(max_length=64, null=True, unique=True),
        ),
    ]
