# Generated by Django 5.2.4 on 2025-07-18 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_transaction_receiving_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='receiving_address',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='sending_address',
        ),
    ]
